/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_yxy_musicplayer_JNITools */

#ifndef _Included_xyz_yxy_musicplayer_JNITools
#define _Included_xyz_yxy_musicplayer_JNITools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_yxy_musicplayer_JNITools
 * Method:    addNum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xyz_yxy_musicplayer_JNITools_addNum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xyz_yxy_musicplayer_JNITools
 * Method:    dump_ncm_file
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_xyz_yxy_musicplayer_JNITools_dump_1ncm_1file
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
